---
title: "Milestone 4"
author: "Sophie Webster"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(rvest)
```

```{r}
tntell <- read.csv("./textntell.csv", stringsAsFactors = FALSE) %>% select(Start, Tracker, Location, Mobile.Number, Comment)
```

```{r cursory plot}
tntell$arranged <- tntell$Location %>% fct_relevel("Annenberg", "Lowell", "Dunster", "Cabot", "Quincy", "Mather", "Pforzheimer", "Winthrop", "Currier", "Leverett", "Eliot", "Adams", "Hillel", "Kirkland", "FlyBy", "Dudley")

# for loop thru all locations? maybe make new frame for number of and folks per house
# tntell %>% filter(Location == "Dunster") %>% count()
# 
# for(i in unique(tntell$Location[1:16])){
#   filter(Location = "i") %>% count()
# }

per_cap <- data.frame(House = unique(tntell$Location), Student.Pop = c(371, 414, 476, 430, 408, 466, 381, 361, 1715, 388, NA, 403, 515, NA, 390, NA), Messages = c(143, 361, 255, 61, 143, 41, 163, 275, 429, 276, NA, 189, 73, NA, 19, NA)) %>% filter(!is.na(Student.Pop))

ggplot(tntell, aes(x = forcats::fct_rev(arranged))) + geom_bar(fill = "#f15b29") + coord_flip() + ggtitle("Who Sent HUDS the Most Messages in 2019?") + labs(y = "", x = "") + theme_light()
       
ggplot(per_cap, aes(x = reorder(House, Messages/Student.Pop), y = (Messages/Student.Pop))) + geom_col(fill = "#f15b29") + coord_flip() + ggtitle("Messages Per Capita By Harvard House") + labs(y = "", x = "") + theme_light() #+ labs(y = "Messages Per Capita")

# do comments per person
# crankiest students

# what about a "today's menu" section that scrapes site and says how people in the past have
# reacted to that entree
# wordcloud

# best rated/ranked quotes
# unique phone numbers versus folks in dhall
# positivity -- train language classifier!
# double check on publishing individual messages
# is this a representative sample of opinions?
```

```{r}
library(readxl)

menu <- read_excel("./FY20 Winter Menu 11052019.xlsx")
   
   meal <- c(rep("Breakfast",24),rep("Lunch",19), rep("Dinner", 16))
   menu <- cbind(menu, meal)
   menu <- menu[-c(48),]
```

```{r}

# pulling out area codes

tntell$area <- sub(".", "", tntell$Mobile.Number)
tntell$area <- substr(tntell$area,1,3) %>% as.double(tntell$area)

url <- paste0("https://www.areacodelocations.info/areacodelist.html")
h <- read_html(url)
html_text(h)
tab <- h %>% html_nodes("table")
tab <- tab %>% html_table() %>% as.data.frame()
tab <- tab[,c(1,2)]
tab$Area.code <- as.numeric(tab$Area.code)

tntell$House <- tntell$Location
located <- left_join(tntell[, c(1,2,4,5,6,7)], tab, by = c("area" = "Area.code"))

located %>%
   ggplot(aes(Location)) + geom_bar() + coord_flip()
mass = 236, ny = 236, ca = 236, tx = 177
# can either group these by region or just look at peeps in mass, ny, ca, tx
# also prob MA encompasses international students
```

